[package]
name = "simulator"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dev-dependencies]
more-asserts = "0.3.1"
rand = "0.8.5"

[dependencies]
bitfield-struct = "0.8.0"
serde = { version = "1.0.215", features = ["derive"], optional = true }
log = "0.4"

[features]
serde = ["dep:serde"]
