[workspace]
resolver = "2"
members = ["simulator", "solvers", "game_data", "raphael-cli", "bindings"]

[package]
name = "raphael-xiv"
version = "0.16.0"
edition = "2021"
default-run = "raphael-xiv"

[dependencies]
simulator = { path = "simulator", features = ["serde"] }
solvers = { path = "solvers" }
game-data = { path = "game_data", features = ["serde"] }

egui = "0.31"
eframe = { version = "0.31", features = ["persistence"] }
egui_extras = { version = "0.31", features = ["http", "webp"] }
# egui_plot = "0.31"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
log = "0.4"
rand = "0.8"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1.7"
gloo-worker = { version = "0.5.0", features = ["futures"] }
web-time = "1.1.0"
web-sys = "0.3"
getrandom = { version = "0.2.15", features = ["js"] }

[[bin]]
name = "webworker"
path = "src/webworker.rs"

[profile.release]
opt-level = 3
lto = "fat"
overflow-checks = false

[profile.test]
opt-level = 3
lto = "thin"
overflow-checks = true
