[workspace]
resolver = "2"
members = [
    "raphael-sim",
    "raphael-solver",
    "raphael-data",
    "raphael-cli",
    "raphael-bindings",
]

[workspace.lints]
clippy.assigning_clones = "warn"
clippy.single_char_pattern = "warn"
clippy.return_self_not_must_use = "warn"
clippy.format_push_string = "warn"
clippy.ref_option = "warn"
clippy.default_trait_access = "warn"
clippy.explicit_iter_loop = "warn"
clippy.unnecessary_semicolon = "warn"
clippy.redundant_closure_for_method_calls = "warn"
clippy.option_if_let_else = "warn"
clippy.use_self = "warn"

[workspace.dependencies]
raphael-sim = { path = "raphael-sim", features = ["serde"] }
raphael-solver = { path = "raphael-solver", features = ["serde"] }
raphael-data = { path = "raphael-data", features = ["serde"] }

[package]
name = "raphael-xiv"
version = "0.18.0"
edition = "2024"
default-run = "raphael-xiv"

[lints]
workspace = true

[dependencies]
raphael-sim = { workspace = true }
raphael-solver = { workspace = true }
raphael-data = { workspace = true }

egui = { git = "https://github.com/KonaeAkira/egui.git" }
eframe = { git = "https://github.com/KonaeAkira/egui.git", features = [
    "persistence",
] }
egui_extras = { git = "https://github.com/KonaeAkira/egui.git", features = [
    "http",
    "webp",
] }

serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
log = "0.4"
rand = "0.8"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1.7"
gloo-worker = { version = "0.5.0", features = ["futures"] }
web-time = "1.1.0"
web-sys = "0.3"
getrandom = { version = "0.2.15", features = ["js"] }

[[bin]]
name = "webworker"
path = "src/webworker.rs"

[profile.release]
opt-level = 3
lto = "fat"
overflow-checks = false

[profile.test]
opt-level = 3
lto = "thin"
overflow-checks = true
