[workspace]
resolver = "2"
members = ["simulator", "solvers", "game_data", "raphael-cli", "bindings"]

[package]
name = "raphael-xiv"
version = "0.16.0"
edition = "2021"
default-run = "raphael-xiv"

[dependencies]
simulator = { path = "simulator", features = ["serde"] }
solvers = { path = "solvers" }
game-data = { path = "game_data", features = ["serde"] }

egui = "0.30.0"

eframe = { version = "0.30.0", features = ["persistence"] }
egui_extras = { version = "0.30.0", features = ["all_loaders"] }
egui_plot = "0.30.0"
image = { version = "0.25", default-features = false, features = ["webp"] }
serde = { version = "1.0.215", features = ["derive"] }
ron = "0.8"
log = "0.4"
rand = "0.8.5"

# workaround for https://github.com/emilk/egui/issues/5491
# remove after updating to egui 0.30.1
profiling = { version = "1.0.16", features = [
    "type-check",
], default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1.7"
gloo-worker = { version = "0.5.0", features = ["futures"] }
web-time = "1.1.0"
# web-sys doesn't follow semver, so version needs to be pinned (https://github.com/emilk/egui/issues/4961)
web-sys = "=0.3.76"

[[bin]]
name = "webworker"
path = "src/webworker.rs"

[profile.release]
lto = "fat"

[profile.test]
opt-level = 3
overflow-checks = true
