[package]
name = "raphael-data"
edition = "2024"
build = "build/main.rs"

[lints]
workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
raphael-sim = { workspace = true }
phf = "0.11.2"
serde = { version = "1.0.215", features = ["derive"], optional = true }

[build-dependencies]
csv = "1.1.6"
phf_codegen = "0.11.2"
serde = { version = "1.0.215", features = ["derive"] }

[features]
serde = ["dep:serde", "raphael-sim/serde"]
