name: Rust

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings" # Fail on all warnings, including Clippy lints

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: cargo check --all-targets --all-features
      - name: Format check
        run: cargo fmt --all --check
      - name: Clippy lint check
        run: cargo clippy --all-targets --all-features
      - name: Run tests
        run: cargo test --verbose --release --package simulator --package solvers --package game-data
